[project]
name = "new-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas>=1.0.1",
    "matplotlib>=3.10.3",
    "seaborn>=0.13.2",
    "shapely>=2.1.1",
]
